## This file is automatically generated
## Standard maketest.g for the homalg project

LoadPackage( "SimplicialObjects" );
Read( "ListOfDocFiles.g" );
example_tree := ExtractExamples( DirectoriesPackageLibrary( "SimplicialObjects", "doc" )[1]![1], "SimplicialObjects.xml", list, 500 );
RunExamples( example_tree, rec( compareFunction := "uptowhitespace" ) );
GAPDocManualLab( "SimplicialObjects" );
QUIT;
